# Virtual Host Por Defecto - Apache mira de uno en uno los hosts escritos aquí,
# y si no coincide con ninguno hosts configurado, el primero es el que 
# procesa las peticiones.
<VirtualHost *:80>
	ServerName default.local
	DocumentRoot "/usr/local/apache2/htdocs/default"

	ErrorLog "logs/default_error.log"
	CustomLog "logs/default_access.log" combined

	<Directory "/urs/local/apache2/htdocs/default">
		AllowOverride None
		Require all granted
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName portal.web.online
	DocumentRoot "/usr/local/apache2/htdocs/portal-online"
	
	ErrorLog "logs/portal_online_error.log"
	CustomLog "logs/portal_online_error.log" combined

	<Directory "/usr/local/apache2/htdocs/portal-online">
		AllowOverride None
		Require all granted
	</Directory>
</VirtualHost>

<VirtualHost *:80>
        ServerName interna-web-offline
        DocumentRoot "/usr/local/apache2/htdocs/interna-offline"

        ErrorLog "logs/interna_offline_error.log"
        CustomLog "logs/interna_offline_error.log" combined

        <Directory "/usr/local/apache2/htdocs/interna-offline">
		Options -Indexes
                AllowOverride None
                Require all granted
        </Directory>

	<Files "app_secret.env">
		Require all denied
	</Files>
</VirtualHost>



